# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(546, 709)
        self.headerText = QtWidgets.QLabel(Dialog)
        self.headerText.setGeometry(QtCore.QRect(230, 30, 71, 61))
        self.headerText.setStyleSheet("color:black;\n"
"font-weight:bold;\n"
"font-size:24pt;\n"
"background-color:none;\n"
"border:none;")
        self.headerText.setObjectName("headerText")
        self.bodyText = QtWidgets.QLabel(Dialog)
        self.bodyText.setGeometry(QtCore.QRect(170, 210, 181, 41))
        self.bodyText.setStyleSheet("font-size:16pt;\n"
"background-color:none;\n"
"border:none;")
        self.bodyText.setObjectName("bodyText")
        self.movies = QtWidgets.QPushButton(Dialog)
        self.movies.setGeometry(QtCore.QRect(150, 450, 241, 71))
        self.movies.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(173, 216, 230); /* Светлый голубой цвет */\n"
"    color: rgb(0, 0, 0); /* Черный цвет текста для контраста */\n"
"    font-size: 30px;\n"
"font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(135, 206, 250); /* Чуть более насыщенный голубой при нажатии */\n"
"}\n"
"\n"
"")
        self.movies.setObjectName("movies")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.headerText.setText(_translate("Dialog", "FINAL"))
        self.bodyText.setText(_translate("Dialog", "Thank\'s for the purchase!"))
        self.movies.setText(_translate("Dialog", "Movies"))











if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
