# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(541, 701)
        self.headerText = QtWidgets.QLabel(Dialog)
        self.headerText.setGeometry(QtCore.QRect(190, 20, 141, 51))
        self.headerText.setStyleSheet("color:#fff;\n"
"font-weight:bold;\n"
"font-size:24pt;\n"
"background-color:none;\n"
"border:none;")
        self.headerText.setObjectName("headerText")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 160, 421, 261))
        self.frame.setStyleSheet("backround-color:rgba(255,255,255,30);\n"
"border:1px solid rdba(255,255,255,40);\n"
"border-radius:6px;\n"
"font-size:12pt;")
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.filmText = QtWidgets.QLabel(self.frame)
        self.filmText.setObjectName("filmText")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.filmText)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.peopleLabel = QtWidgets.QLabel(self.frame)
        self.peopleLabel.setObjectName("peopleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.peopleLabel)
        self.listUsers = QtWidgets.QListWidget(self.frame)
        self.listUsers.setObjectName("listUsers")
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listUsers.addItem(item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.listUsers)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.headerText.setText(_translate("Dialog", "MOVIE INFO"))
        self.filmText.setText(_translate("Dialog", "FILM:"))
        self.peopleLabel.setText(_translate("Dialog", "PEOPLE:"))
        __sortingEnabled = self.listUsers.isSortingEnabled()
        self.listUsers.setSortingEnabled(False)
        self.listUsers.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
