# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(QtWidgets.QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(547, 713)
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("backround-color:blue;\n"
"font-family:Noto Sans SC;")
        self.headerText = QtWidgets.QLabel(Dialog)
        self.headerText.setGeometry(QtCore.QRect(170, 40, 221, 41))
        self.headerText.setStyleSheet("color:black;\n"
"font-weight:bold;\n"
"font-size:24pt;\n"
"background-color:none;\n"
"border:none;")
        self.headerText.setObjectName("headerText")
        self.registerButton = QtWidgets.QPushButton(Dialog)
        self.registerButton.setGeometry(QtCore.QRect(270, 550, 241, 51))
        self.registerButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(128, 128, 128); /* Серый цвет */\n"
"    color: rgb(255, 255, 255); /* Белый цвет текста */\n"
"    font-size: 33px;\n"
"font-weight:500;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(169, 169, 169); /* Более светлый серый при нажатии */\n"
"}\n"
"")
        self.registerButton.setObjectName("registerButton")
        self.main_frame = QtWidgets.QFrame(Dialog)
        self.main_frame.setGeometry(QtCore.QRect(40, 150, 471, 361))
        self.main_frame.setStyleSheet("backround-color:rgba(255,255,255,30);\n"
"border:1px solid rdba(255,255,255,40);\n"
"border-radius:7px;\n"
"")
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usernameText = QtWidgets.QLabel(self.main_frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(14)
        self.usernameText.setFont(font)
        self.usernameText.setStyleSheet("font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.usernameText.setObjectName("usernameText")
        self.verticalLayout_2.addWidget(self.usernameText)
        self.usernamInput = QtWidgets.QLineEdit(self.main_frame)
        self.usernamInput.setMinimumSize(QtCore.QSize(0, 50))
        self.usernamInput.setMaximumSize(QtCore.QSize(16777215, 20))
        self.usernamInput.setSizeIncrement(QtCore.QSize(0, 0))
        self.usernamInput.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        font.setKerning(True)
        self.usernamInput.setFont(font)
        self.usernamInput.setText("")
        self.usernamInput.setObjectName("usernamInput")
        self.verticalLayout_2.addWidget(self.usernamInput)
        self.passwordText = QtWidgets.QLabel(self.main_frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(14)
        self.passwordText.setFont(font)
        self.passwordText.setStyleSheet("font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.passwordText.setObjectName("passwordText")
        self.verticalLayout_2.addWidget(self.passwordText)
        self.passwordInput = QtWidgets.QLineEdit(self.main_frame)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 50))
        self.passwordInput.setMaximumSize(QtCore.QSize(16777215, 20))
        self.passwordInput.setSizeIncrement(QtCore.QSize(0, 0))
        self.passwordInput.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        font.setKerning(True)
        self.passwordInput.setFont(font)
        self.passwordInput.setText("")
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout_2.addWidget(self.passwordInput)
        self.verifyPasswordText = QtWidgets.QLabel(self.main_frame)
        self.verifyPasswordText.setStyleSheet("font-size:14pt;\n"
"background-color:none;\n"
"border:none;")
        self.verifyPasswordText.setObjectName("verifyPasswordText")
        self.verticalLayout_2.addWidget(self.verifyPasswordText)
        self.verifyPasswordInput = QtWidgets.QLineEdit(self.main_frame)
        self.verifyPasswordInput.setMinimumSize(QtCore.QSize(0, 50))
        self.verifyPasswordInput.setMaximumSize(QtCore.QSize(16777215, 20))
        self.verifyPasswordInput.setSizeIncrement(QtCore.QSize(0, 0))
        self.verifyPasswordInput.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setPointSize(12)
        font.setKerning(True)
        self.verifyPasswordInput.setFont(font)
        self.verifyPasswordInput.setText("")
        self.verifyPasswordInput.setObjectName("verifyPasswordInput")
        self.verticalLayout_2.addWidget(self.verifyPasswordInput)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.headerText.setText(_translate("Dialog", "REGISTER"))
        self.registerButton.setText(_translate("Dialog", "register"))
        self.usernameText.setText(_translate("Dialog", "username:"))
        self.passwordText.setText(_translate("Dialog", "password:"))
        self.verifyPasswordText.setText(_translate("Dialog", "verify password:"))


